http_client:	http_client.o
	g++ -g -o http_client http_client.o
http_server:	http_server.o
	g++ -g -o http_server http_server.o
http_client.o:	http_client.c
	g++ -g -c http_client.c
http_server.o: http_server.c
	g++ -g -c http_server.c
